### ISSUE TITLE
click event

### ISSUE THREAD

**Issue by jacklee0223** [jacklee0223/memory_game#1]
https://github.com/jacklee0223/memory_game

Hi, I am trying to create an Event Listener that will change the background image for each of the tiles when clicked. However, I cannot get it to work no matter what I try. Initially, my plan was to use use addClass, but realized that it might compromise my other functions. Would anyone please help me figure it out? My code looks like the following:

var board = ['1','1','2','2','3','3','4','4','5','5','6','6','7','7','8','8','9','9'];
var boardEl = document.getElementsByClassName('tiles');
console.log (boardEl);

JS:
for(var i = 0; i < boardEl.length; i++) {
  boardEl[i].addEventListener('click', function () {
    console.log(this);
    $('.tiles').eq(i).css('background-image', ('sc' + board[i] + '.png'));
  });
}

HTML:
<div class="memoryBoard">
  <div class="tiles" id="tile0"></div>
  <div class="tiles" id="tile1"></div>
  <div class="tiles" id="tile2"></div> ...

CSS:
.memoryBoard .tiles {
    border: 1px solid black;
    font-size: 20px;
    text-align: center;
    height: 175px;
    width: 100px;
    display: inline-block;
    background-size: cover;
    background-image: url("scb.png"); }

**Comment by jacklee0223** [comment]
Lawrence helped me make the images appear when clicked, but it's not pulling from the board that randomized in the beginning. I've tried inserting board [i] in the place of this.id, but it's not really working. I will try to figure it out, but any input will be appreciated.

for(var i = 0; i < boardEl.length; i++) {
  boardEl[i].addEventListener('click', function () {
    console.log(this);
    $(this).css('background-image', "url(css/sc" + this.id + ".png" + ")");
  });
}

**Comment by h4w5** [comment]
If you still need help, but the problem changes, the procedure is generally to [create a new issue that you reference in this one](https://github.com/blog/957-introducing-issue-mentions) by writing the issue number preceded by an octothorpe: like `#2`. You also close this one (as you did). Good luck!
