### ISSUE TITLE
Getting specific event array out of for loop

### ISSUE THREAD

**Issue by jacklee0223** [jacklee0223/memory_game#2]
Game: Memory 
https://github.com/jacklee0223/memory_game

1. What User Story (or feature) are you working on?
-Making flipped card turn back when there is no match between the two
-Switching players after 2 flips

2. What error are you getting?
-Currently, the cards will flip and stay flipped upon click. Also, when a single card is clicked twice, the player change mechanic takes place. I am trying to figure out a way to somehow separate out flipped cards that matches and those that aren't. The biggest problem for me is that I am using for-loop on my event listener. I am not sure if there is any way to draw out whatever is in boardEl[i] out of the function and insert a function in my check match mechanism to change class when there are matching cards.

3. How have you attempted to fix your error?
-I tried to incorporate click event into a if-else statement. First of all, I added a function to remove class and add class on the event listener:

```Javascript
for(var i = 0; i < boardEl.length; i++) {
  boardEl[i].addEventListener('click', function () {
    var idx = parseInt(this.id) - 1;
    $(this).css('background-image', "url(css/img/sc" + shuffled_board[idx] + ".png" + ")");
    //////Here////////
   $(this).removeClass('tiles').addClass('tilesF');
    //////////////////
    tiles_flipped ++;
    console.log(this);
    memory_values.push(shuffled_board[idx]);
    match();
    getWinner();
  });
}
```
-I also tried adding the same function to the match checker mechanism:

```Javascript
function match() {
  if(currentPlayer === 'player1') {
    if(memory_values[1] === undefined) {
      console.log('one more');
      return;
    } else if (memory_values[0] === memory_values[1]) {
      console.log('match');
      player1_Score++
      $('#player1_Score').html(player1_Score);
/////////////Here////////////
      $(this).removeClass('tiles').addClass('tilesF');
//////////////////////////////
      changeTurn();
      memory_values = [];
    } else if (memory_values[0] !== memory_values[1]){
      console.log('no match');
      changeTurn();
      memory_values = [];
    }
  } else {
      if(memory_values[1] === undefined) {
      console.log('one more');
      return;
    } else if (memory_values[0] === memory_values[1]) {
      console.log('match');
      player2_Score++
      $('#player2_Score').html(player2_Score);
      changeTurn();
      memory_values = [];
    } else if (memory_values[0] !== memory_values[1]){
      console.log('no match');
      changeTurn();
      memory_values = [];
    }
  }
};
```

- I've quickly realized that $(This) won't work outside of the event listener for-loop. So I asked Sarah for advice and she recommended that I follow the logic of the following pseudo-code:

```Javascript
memory_values=[];

randomTile = "randomNumber" + "tile id"

match 
    if playerScore ++
    then take tile id from memory_value
    set class to tileF
```

-The general idea of Sarah's pseudo-code is that I take the arrays in memory_values[] to the tile ID and then concatenate to the randomTile variable. However, I am only partly understanding it conceptually, and don't even know where to begin in terms of implementing into code. I will try a few different things until tonight, but I have a feeling I won't be getting anywhere without figuring out a way to pull for-loop array in a specific click event out of the function.

Thanks.

**Comment by h4w5** [comment]
Hey Jeong!

First: use three backticks to surround your code, so that it formats as code in Markdown!

For example:

<pre>
```javascript
// here is my code!
var good = "job";
```
</pre>

Second: good thought with using an `if` statement with your click event! However, these things get very
complicated, as you know.

Third: I don't quite understand Sarah's example as you're explaining it, so I can't comment on that.

So, I'll check out your code further to and comment again with a suggestion.

In the meantime, please edit the issue to use better-formatted Markdown with your code!

**Comment by h4w5** [comment]
Also, @jacklee0223, push your most recent version of your code!

**Comment by h4w5** [comment]
Alright, looked at your code. It's not bad! Some really nice stuff in there. I like your choices with your data modeling.

Your current click event looks like this:

```javascript
for(var i = 0; i < boardEl.length; i++) {
  boardEl[i].addEventListener('click', function () {
    var idx = parseInt(this.id) - 1;
    $(this).css('background-image', "url(css/img/sc" + shuffled_board[idx] + ".png" + ")");
    tiles_flipped ++;
    console.log(this);
    memory_values.push(shuffled_board[idx]);
    match();
    getWinner();
  });
}
```

I'll change it to this to make it more readable:

```javascript
var userClicksCard = function(event) {
  // get the index of the clicked card
  var idx = parseInt(this.id) - 1;
  
  // show the image associated with this card
  $(this).css('background-image', "url(css/img/sc" + shuffled_board[idx] + ".png" + ")");
  tiles_flipped ++;

  // update values
  memory_values.push(shuffled_board[idx]);

  // check if there is a match
  match();

 // check if there is a winner
  getWinner();
};

for(var i = 0; i < boardEl.length; i++) {
  boardEl[i].addEventListener('click', userClicksCard);
}
```

Alright! Now, here is how I would change that function to make the clicking make it flip back:

```javascript
var userClicksCard = function(event) {
  // get the index of the clicked card
  var idx = parseInt(this.id) - 1;
  
  // show the image associated with this card
  $(this).css('background-image', "url(css/img/sc" + shuffled_board[idx] + ".png" + ")");
  tiles_flipped++;

  // update values
  memory_values.push(shuffled_board[idx]);

  // ! right here ! 
  // 1. check if there is a match
  //   a. if there is a match, grab this value and the last value from memory_values,
  //       and make them both stay up / disappear / whatever they do on match
  //   b. if there is NOT a match, put an action in a setTimeout that will reset the
  //       background images of the last two values in memory_values

  if (match()) {
    // ... (a)
  } else {
    setTimeout(function () {
      // ... (b)
    }, 5000);
  } // not sure if that is the exact right syntax for setTimeout

 // check if there is a winner
  getWinner();
};
```

Good luck! Let me know if that helps!

**Comment by jacklee0223** [comment]
Thank you!

I will try incorporating your advice and see how things turn out.
Hope you have a good night and see you tomorrow.

**Comment by h4w5** [comment]
OK then, marking as closed.
